version: '3.7'

services:
    web:
        build: ./security_analysis_web_app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./security_analysis_web_app:/security/analysis_web_app/security_analysis_web_app
        ports:
            - "8000:8000"
        env_file:
            - ./security_analysis_web_app/.env.dev.docker
        depends_on:
            - db
    db:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_DB=stock_db
        - POSTGRES_USER=stock_user
        - POSTGRES_PASSWORD=stock_password

volumes:
  postgres_data: