version: '3.7'

services:
    web:
        build: ./security_analysis_web_app
        command: gunicorn security_analysis_web_app.wsgi:application --bind 0.0.0.0:8000
        ports:
            - "8000:8000"
        env_file:
            - ./security_analysis_web_app/.env.prod
        depends_on:
            - db
    db:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ./security_analysis_web_app/.env.prod.db

volumes:
  postgres_data: