# Generated by Django 2.2.1 on 2020-05-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker_symbol', models.CharField(help_text="A company's ticker symbol", max_length=8, primary_key=True, serialize=False)),
                ('company_name', models.CharField(help_text="The companies' name", max_length=40)),
                ('price', models.IntegerField(help_text='The price of the stock')),
                ('daily_change', models.IntegerField(help_text='The daily change (in dollars) of the stock')),
                ('year_high', models.IntegerField(help_text='The high price of the stock during the year')),
                ('year_low', models.IntegerField(help_text='The low price of the stock during the year')),
                ('daily_percent', models.IntegerField(help_text='The daily percent change of the stock')),
                ('last_updated_date', models.DateField(auto_now=True, help_text='The date when the stock information was last updated')),
                ('date_added', models.DateField(auto_now_add=True, help_text='The date the stock was added to the database')),
                ('streak', models.IntegerField(help_text='Represents a streak of positive or negative earnings.')),
            ],
        ),
    ]
