# Generated by Django 2.2.1 on 2020-07-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='daily_change',
            field=models.DecimalField(decimal_places=2, help_text='The daily change (in dollars) of the stock', max_digits=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='daily_percent',
            field=models.DecimalField(decimal_places=2, help_text='The daily percent change of the stock', max_digits=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='The price of the stock', max_digits=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='year_high',
            field=models.DecimalField(decimal_places=2, help_text='The high price of the stock during the year', max_digits=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='year_low',
            field=models.DecimalField(decimal_places=2, help_text='The low price of the stock during the year', max_digits=8),
        ),
    ]
