# Generated by Django 2.2.1 on 2020-07-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0002_auto_20200703_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='references',
            field=models.IntegerField(default=0, help_text='Represents number of user account references to the stock.'),
        ),
    ]
