version: '3.7'

services:
    web:
        build:
            context: ./security_analysis_web_app
            dockerfile: Dockerfile.prod
        command: gunicorn security_analysis_web_app.wsgi:application --bind 0.0.0.0:8000
        volumes:
        - static_volume:/security_analysis_web_app/web/static
        expose:
            - 8000
        env_file:
            - ./security_analysis_web_app/.env.staging
        depends_on:
            - db
    db:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ./security_analysis_web_app/.env.staging.db
    nginx-proxy:
        container_name: nginx-proxy
        build: ./security_analysis_web_app/nginx
        restart: always
        volumes:
           - static_volume:/security_analysis_web_app/web/static
           - certs:/etc/nginx/certs
           - html:/usr/share/nginx/html
           - vhost:/etc/nginx/vhost.d
           - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 443:443
            - 80:80
        depends_on:
            - web
    nginx-proxy-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        env_file:
         - ./security_analysis_web_app/.env.staging.proxy-companion
        volumes:
         - /var/run/docker.sock:/var/run/docker.sock:ro
         - certs:/etc/nginx/certs
         - html:/usr/share/nginx/html
         - vhost:/etc/nginx/vhost.d
    depends_on:
      - nginx-proxy


volumes:
  postgres_data:
  static_volume:
  certs:
  html:
  vhost: